### ISSUE TITLE
Application not responding while trying to decrypt folder infected with Onyx2

### ISSUE THREAD

**Issue by Suman99pro** [Truesec/TSDecryptors#4]
I tried to use TSDecryptor to encrypt the files infected with Onyx2 Ransomware. After a while the Application stops responding. It happens in the Parsing Files Phase.
<img width="616" alt="image" src="https://github.com/user-attachments/assets/3bc68fdf-3714-4e08-89b6-c3b0f03e0fcd">

**Comment by alexandera-truesec** [comment]
Hi, 

Thanks for reporting this issue. 

I believe that the decryption is still running in the background. We will try to figure out why the user interface becomes non-responsive in some cases.

In the meanwhile, you can watch the progress by opening Resource Monitor (resmon). You will notice that the decryptor is reading and writing the files. 

<img width="650" alt="image" src="https://github.com/user-attachments/assets/13100b57-3e7e-4363-b7d1-3f90b29a7601">

**Comment by Suman99pro** [comment]
Thank you for the response. I will do as per your recommendations.
